version: "3.8"

services:
  tfg-mongo:
    image: mongo:7
    container_name: tfg-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin1234
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - tfg-net

  tfg-api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: tfg-api
    environment:
      PORT: 3000
      MONGO_URI: "mongodb://admin:admin1234@tfg-mongo:27017"
      DATABASE_NAME: mydatabase
      JWT_SECRET: "macarrones_con_queso"
    ports:
      - "3000:3000"
    volumes:
      - ./API/uploads:/app/uploads
    depends_on:
      - tfg-mongo
    networks:
      - tfg-net

  tfg-web:
    build:
      context: ./WEB
      dockerfile: Dockerfile
    container_name: tfg-web
    ports:
      - "4200:4200"
    depends_on:
      - tfg-api
    networks:
      - tfg-net

volumes:
  mongo_data:

networks:
  tfg-net:
    driver: bridge
