# API/Dockerfile
FROM node:22-bookworm

WORKDIR /app

# Copiamos primero los package.json para aprovechar la cache de Docker
COPY package*.json ./

# Instalamos las dependencias normales y las especificas de tu guia
RUN npm install && \
    npm install mongodb multer cors

# Copiamos el resto del codigo de la API
COPY . .

# Exponemos el puerto de la API
EXPOSE 3000

# Comando para arrancar
CMD ["npm", "start"]