#### GET
GET http://localhost:3000/atributes
Accept: application/json 

### POST
POST http://localhost:3000/atributes
Content-Type: application/json

{
  "name": "Color",
  "values": []
}

### GET NAME
GET http://localhost:3000/atributes/C
Accept: application/json 

### PUT values
PUT http://localhost:3000/atributes/699614419d17b97c4bfe2363
Content-Type: application/json

{
  "value": "Azul"
}

### DELETE
DELETE http://localhost:3000/atributes/699614259d17b97c4bfe2361
Accept: application/json 