#### GET
GET http://localhost:3000/atributes
Accept: application/json 

### POST
POST http://localhost:3000/atributes
Content-Type: application/json

{
  "name" : "Color",
  "value" : "Rojo"
}

### GET NAME
GET http://localhost:3000/atributes/Colo
Accept: application/json 

### DELETE
DELETE http://localhost:3000/atributes/699461e682d609f5b8eebfdd
Accept: application/json 