# WEB/Dockerfile
FROM node:22-bookworm

WORKDIR /app

# Copiamos los package.json
COPY package*.json ./

# Instalamos dependencias con la bandera legacy e instalamos Angular CLI global
RUN npm install --legacy-peer-deps && \
    npm install -g @angular/cli

# Copiamos el resto del codigo frontend
COPY . .

# Exponemos el puerto de Angular
EXPOSE 4200

# Arrancamos exponiendo el host para que sea accesible desde fuera del contenedor
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4200"]