# WEB/Dockerfile
FROM node:22-bookworm

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps && \
    npm install -g @angular/cli

COPY . .

EXPOSE 4200

CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4200"]